//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/M2Message.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/M2Message.xsd", IsNullable=false)]
public partial class M2Message {
    
    private string transferGuidField;
    
    private string addressField;
    
    private string clientIdField;
    
    private string contentTypeField;
    
    /// <remarks/>
    public string TransferGuid {
        get {
            return this.transferGuidField;
        }
        set {
            this.transferGuidField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    public string ContentType {
        get {
            return this.contentTypeField;
        }
        set {
            this.contentTypeField = value;
        }
    }
}
